title: "Yash Sharma"
email: yash37158@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
Hey ! I'm yash sharma from india , currently pursuing my bachelors in CS at Amity University Mumbai .
Skill set include Front End Web Develeopment , Android Development and beginner in open souce contribution.
baseurl: "/" 
url: "https://yash37158/githun/io" 
twitter_username: yash37158
github_username:  yash37158

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg

theme: jekyll-theme-cayman